language: python

python:
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt --upgrade

script:
  - pytest -v -s
  - py.test -v --cov=plugboard --cov-report xml


after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION